version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: xtsusaku-homer_server_1
      APP_PORT: 8080
    
  server:
    image: b4bz/homer:latest
    volumes:
      - ${APP_DATA_DIR}/config:/config
      - ${APP_DATA_DIR}/assets:/www/assets
    environment:
      - PUID=1000
      - PGID=1000
      - INIT_ASSETS=1
    restart: on-failure
    user: "1000:1000"
    init: true